### ISSUE TITLE
error upon start.

### ISSUE THREAD

**Issue by merimus** [GiantVM/QEMU#4]
Linux-DSM built and configured.
Qemu build, attempting to boot and get this error.
One note: I am running an ubuntu instance within virtualbox with the ICH9 chipset selected.

BP
$ sudo x86_64-softmmu/qemu-system-x86_64 --nographic -hda ubuntu-server.img -cpu host -machine kernel-irqchip=off -smp 4 -m 512  --enable-kvm -serial mon:stdio -local-cpu 2,start=0,iplist="127.0.0.1 127.0.0.1" -vnc :0
CPU Info
Total: 4
Local: 2 [0-1]
Remote: 2[ 2 3 ]
KVM API version[12], QEMU version[12]
CPU 2 is remote CPU, pause
CPU 3 is remote CPU, pause
start kvm dsm server, total memory size: 536870912
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
error: msi send vector in range 0-15
error: cannot find current apic
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
QEMU nums: 2, Total CPU nums: 4, CPU per QEMU: 2
connect_io_router...
connecting 127.0.0.1:40001
Connecting...
QEMU 0 listen on TCP socket 127.0.0.1:40000
connecting io router done
connect_io_router done
QEMU 0 set kvmclock: 0
error: kvm run failed Operation not permitted
EAX=00000000 EBX=00000000 ECX=00000010 EDX=000f2d7e
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00007000
EIP=000f2d7e EFL=00000006 [-----P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 00000000 ffffffff 00c09300 DPL=0 DS   [-WA]
CS =0008 00000000 ffffffff 00c09b00 DPL=0 CS32 [-RA]
SS =0010 00000000 ffffffff 00c09300 DPL=0 DS   [-WA]
DS =0010 00000000 ffffffff 00c09300 DPL=0 DS   [-WA]
FS =0010 00000000 ffffffff 00c09300 DPL=0 DS   [-WA]
GS =0010 00000000 ffffffff 00c09300 DPL=0 DS   [-WA]
LDT=0000 00000000 0000ffff 00008200 DPL=0 LDT
TR =0000 00000000 0000ffff 00008b00 DPL=0 TSS32-busy
GDT=     000f7070 00000037
IDT=     000f70ae 00000000
CR0=00000011 CR2=00000000 CR3=00000000 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=c0 e2 0f 00 0f b7 d2 8d 44 24 02 e8 31 c8 ff ff 83 c4 28 c3 <53> 83 ec 2c e8 0a cb ff ff bb 00 00 00 40 8d 44 24 18 89 44 24 04 8d 44 24 14 89 04 24 8d

AP
$ sudo x86_64-softmmu/qemu-system-x86_64 --nographic -hda ubuntu-server.img -cpu host -machine kernel-irqchip=off -smp 4 -m 4096  --enable-kvm -serial mon:stdio -local-cpu 2,start=2,iplist="127.0.0.1 127.0.0.1"
CPU Info
Total: 4
Local: 2 [2-3]
Remote: 2[ 0 1 ]
KVM API version[12], QEMU version[12]
CPU 0 is remote CPU, pause
CPU 1 is remote CPU, pause
start kvm dsm server, total memory size: 4294967296
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
error: msi send vector in range 0-15
error: cannot find current apic
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
run_on_cpu: not local CPU, ignore here. This could be a latent bug.
QEMU nums: 2, Total CPU nums: 4, CPU per QEMU: 2
connect_io_router...
connecting 127.0.0.1:40000
Connecting...
QEMU 1 listen on TCP socket 127.0.0.1:40001
connecting io router done
connect_io_router done
kvmclock sync RTT[70195848]
QEMU 2 set kvmclock: 35295372

**Comment by xianliang66** [comment]
Hello,

I found two possible problems.
1. In the case of VirtualBox, you need to make sure it supports nested virtualization, in which the hypervisor virtualizes a faked VT-x environment for GiantVM. It might not work.
2. The error code is permission denied. Try sudo or add the users to ACL.

**Comment by merimus** [comment]
Nested virtualization is indeed enabled, and both qemu commands were run with sudo.

**Comment by merimus** [comment]
issues does not show when using qemu... appears to be an issue with apic emulation in virtualbox.
