### ISSUE TITLE
I'm encountering an error when running QEMU to start a virtual machine. 

### ISSUE THREAD

**Issue by Qiang-Xuu** [GiantVM/QEMU#7]
Could you please help me look into it? Thank you！

**cmd**
sudo x86_64-softmmu/qemu-system-x86_64 --nographic -hda ubuntu-server.img -cpu host -machine kernel-irqchip=off -smp 4 -m 4096  --enable-kvm -serial mon:stdio -local-cpu 2,start=0,iplist="127.0.0.1 127.0.0.1" -vnc :0

CPU Info
Total: 4
Local: 2 [0-1]
Remote: 2[ 2 3 ]
KVM API version[12], QEMU version[12]
CPU 2 is remote CPU, pause
CPU 3 is remote CPU, pause
start kvm dsm server, total memory size: 4294967296
qemu-system-x86_64: /home/xu/Documents/DSM/QEMU-master/target-i386/kvm.c:1809: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
Aborted

**sysinfo**
Jan 13 00:03:09 ubuntu gnome-software[2060]: message repeated 4 times: [ Failed to load snap icon: (null): local snap has no icon]
Jan 13 00:03:36 ubuntu kernel: [  139.288400] kvm_dsm_init: Enable kvm dsm mode, this kvm instance will be node-0
Jan 13 00:03:36 ubuntu kernel: [  139.288402] kvm_dsm_init: kvm_dsm_init: kvm 0 use TCP connection
Jan 13 00:03:50 ubuntu kernel: [  153.076519] kvm [2154]: vcpu0, guest rIP: 0xfff0 unhandled wrmsr: 0x38d data 0x0
Jan 13 00:03:50 ubuntu kernel: [  153.310607] kvm-dsm: node-0 stopping dsm server
Jan 13 00:03:51 ubuntu kernel: [  153.385048] kvm-dsm: node-0 most frequently read 10 pages
Jan 13 00:03:51 ubuntu kernel: [  153.385049] 	vfn	gfn	read	write
Jan 13 00:03:51 ubuntu kernel: [  153.385051] 	0	[4294967296,0]	0	1835376104
Jan 13 00:03:51 ubuntu kernel: [  153.385051] 	ffff8a8163ae0080	[1,1]	01752236032
Jan 13 00:03:51 ubuntu kernel: [  153.385052] 	ffffb4d184a8fc40	[18446744072250705459,0]	0	2836122531
Jan 13 00:03:51 ubuntu kernel: [  153.385052] 	0	[18446661410699672680,188]	4294967295	2836146052
Jan 13 00:03:51 ubuntu kernel: [  153.385053] 	ffff8a816632ee00	[18446614887060607744,192]	4294937217	1835376000
Jan 13 00:03:51 ubuntu kernel: [  153.385053] 	ffff8a8163ae1240	[18446614887060602880,128]	4294937217	1795829120
Jan 13 00:03:51 ubuntu kernel: [  153.385053] 	ffff8a8163ae0000	[18446614887059326912,0]	0	2225667272
Jan 13 00:03:51 ubuntu kernel: [  153.385054] 	ffffffffa987e194	[0,0]	0582
Jan 13 00:03:51 ubuntu kernel: [  153.385054] 	ffff8a816d659d80	[18446661410699672744,0]	4294937217	1672347648
Jan 13 00:03:51 ubuntu kernel: [  153.385055] 	7fffffffffffffff	[18446661410699673052,0]	4294937217	2225667296
Jan 13 00:03:51 ubuntu kernel: [  153.385055] kvm-dsm: node-0 most frequently written 10 pages
Jan 13 00:03:51 ubuntu kernel: [  153.385055] 	vfn	gfn	read	write
Jan 13 00:03:51 ubuntu kernel: [  153.385056] 	ffffffffa987e686	[9223372036854775807,96]	4294948049	2844268677
Jan 13 00:03:51 ubuntu kernel: [  153.385056] 	ffff8a8163ae0000	[0,243]4294967295	2842990379
Jan 13 00:03:51 ubuntu kernel: [  153.385057] 	ffff8a8164f03200	[18446614887179538432,144]	4294948049	2837803151
Jan 13 00:03:51 ubuntu kernel: [  153.385057] 	ffff8a8164f06250	[582,0]01693475248
Jan 13 00:03:51 ubuntu kernel: [  153.385058] 	ffff8a8164f06238	[18446744072261389056,0]	4294967295	1693475248
Jan 13 00:03:51 ubuntu kernel: [  153.385058] 	ffff8a8164f06238	[18446744072261389056,152]	4294948049	2842990303
Jan 13 00:03:51 ubuntu kernel: [  153.385058] 	ffff8a8164f061b0	[18446661410699673008,91]	4294967295	1693475248
Jan 13 00:03:51 ubuntu kernel: [  153.385059] 	ffffb4d184a8fdd8	[18446744072252325814,176]	4294937217	1791283200
Jan 13 00:03:51 ubuntu kernel: [  153.385059] 	ffff8a8164f06238	[18446661410699673096,126]	4294967295	1693475200
Jan 13 00:03:51 ubuntu kernel: [  153.385060] 	0	[18446614887055392768,19]	4294967295	2225667624
Jan 13 00:03:51 ubuntu kernel: [  153.385060] kvm-dsm: node-0 total page faults 0
Jan 13 00:03:51 ubuntu kernel: [  153.385061] kvm-dsm: node-0 average bytes 0

**dmesg**
[  765.988587] kvm_dsm_init: Enable kvm dsm mode, this kvm instance will be node-0
[  765.988589] kvm_dsm_init: kvm_dsm_init: kvm 0 use TCP connection
[  770.798746] kvm [2635]: vcpu0, guest rIP: 0xfff0 unhandled wrmsr: 0x38d data 0x0
[  771.033434] kvm-dsm: node-0 stopping dsm server
[  771.090615] kvm-dsm: node-0 most frequently read 10 pages
[  771.090616] 	vfn	gfn	read	write
[  771.090617] 	0	[4294967296,0]	0	1835113960
[  771.090617] 	ffff8a8165072e00	[1,1]	0	1757584896
[  771.090618] 	ffffb4d182817c40	[18446744072250705459,0]	0	2836122531
[  771.090618] 	0	[18446661410663529576,188]	4294967295	2836146052
[  771.090619] 	ffff8a81639329c0	[18446614887083229312,192]	4294937217	1835113856
[  771.090619] 	ffff8a8165073fc0	[18446614887083224448,128]	4294937217	2850100480
[  771.090620] 	ffff8a8165072d80	[18446614887059350720,0]	0	2189524168
[  771.090620] 	ffffffffa987e194	[0,0]	0	582
[  771.090621] 	ffff8a816d619d80	[18446661410663529640,128]	4294937217	1694969216
[  771.090621] 	7fffffffffffffff	[18446661410663529948,0]	4294937217	2189524192
[  771.090622] kvm-dsm: node-0 most frequently written 10 pages
[  771.090622] 	vfn	gfn	read	write
[  771.090622] 	ffffffffa987e686	[9223372036854775807,96]	4294948049	2844268677
[  771.090623] 	ffff8a8165072d80	[0,243]	4294967295	2842990379
[  771.090623] 	ffff8a8166499e00	[18446614887179538432,144]	4294948049	2837803151
[  771.090624] 	ffff8a8166498d50	[582,0]	0	1716096176
[  771.090624] 	ffff8a8166498d38	[18446744072261389056,0]	4294967295	1716096176
[  771.090625] 	ffff8a8166498d38	[18446744072261389056,152]	4294948049	2842990303
[  771.090625] 	ffff8a8166498cb0	[18446661410663529904,91]	4294967295	1716096176
[  771.090625] 	ffffb4d182817dd8	[18446744072252325814,176]	4294937217	1791283200
[  771.090626] 	ffff8a8166498d38	[18446661410663529992,126]	4294967295	1716096128
[  771.090626] 	0	[18446614886181928960,19]	4294967295	2189524520
[  771.090627] kvm-dsm: node-0 total page faults 0
[  771.090627] kvm-dsm: node-0 average bytes 0
[  771.090627] kvm-dsm: node-0 average tx latency 0us

**Comment by DeeEll-X** [comment]
Hi, maybe you can try setting ignore_msrs=1 for kvm and boot again?

**Comment by SoulIndream** [comment]
Thank you for your guidance. After setting "ignore_msrs=1," the system seems to be running, but I'm still encountering the following errors: "error: msi send vector in range 0-15; error: cannot find current apic; run_on_cpu: not local CPU, ignore here. This could be a latent bug." Additionally, the keyboard in VNC Viewer is not responding. I am using the version VNC-Viewer-6.22.826-Linux-x64.deb, as I couldn't find the version you mentioned.
![微信图片_20240115164631](https://github.com/GiantVM/QEMU/assets/54839011/8e90514c-0589-443d-9028-bf38b9bb7170)

![Uploading 微信截图_20240115164833.png…]()

**Comment by Qiang-Xuu** [comment]
Thank you very much for your help. The system seems to be running now, but I notice there are some error messages. I'm not sure if there is a problem.
![1705396881989](https://github.com/GiantVM/QEMU/assets/54839011/8ccb1af3-a34c-46b7-acdb-b43d5019973d)

**Comment by DeeEll-X** [comment]
Good! Just ignore these messages.
